# External gems
gems:
  - jekyll-archives
  - jekyll-sitemap

# Site settings
title: “Wu-xiaoshen”
subtitle:    读书    |    思维    |    精进
email: wuxiaoshen@shu.edu.cn
name: Wu-xiaoshen
description: 初学者
baseurl: "/" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
cover: "assets/images/twitter.jpg"
logo:  "初学者" #"assets/images/logo/logo5.png"

# Build settings
markdown: kramdown
paginate: 10
paginate_path: "/page:num/"
inter_post_navigation: True
highlightjs_theme: "monokai_sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled: 
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: #bencentra

# Google analytics
ga_tracking_id: 

# Category descriptions (for archive pages)
descriptions:
  - cat: 读书
    desc: "读书: 从别人的眼中认识世界."

  - cat: 代码
    desc: "代码： 从自己的眼中创造世界."

  - cat: 思维
    desc: "思维： 你眼中的世界是你认为的世界."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: Twitter
    icon: twitter
    username: 
    url: 
    desc: 
    share_url: 
    share_title: 
    share_link: 

  - name: Facebook
    icon: facebook
    username: 
    url: 
    desc: 
    share_url: 
    share_title: 
    share_link: 

  - name: GitHub
    icon: github
    username: wuxiaoxiaoshen
    url: https://github.com/wuxiaoxiaoshen
    desc: Fork me on GitHub
    share_url:
    share_title:
    share_link:

  - name: LinkedIn
    icon: linkedin
    username: 
    url: 
    desc: 
    share_url: 
    share_title: 
    share_link: 

  - name: Google+
    icon: google-plus
    username: 
    url: 
    desc: Add me to your Circles
    share_url: //plus.google.com/share
    share_title: ?title=
    share_link: "&amp;url="

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share_url: 
    share_title: 
    share_link:

  - name: Instagram
    icon: instagram
    username: 
    url: 
    desc: Follow me on Instagram
    share_url: 
    share_title: 
    share_link:

  - name: Pinterest
    icon: pinterest
    username: 
    url: 
    desc: Follow me on Pinterest
    share_url: 
    share_title: 
    share_link:

  - name: SoundCloud
    icon: soundcloud
    username: 
    url: 
    desc: Follow me on SoundCloud
    share_url: 
    share_title: 
    share_link:

  - name: Tumblr
    icon: tumblr
    username: 
    url: 
    desc: Follow me on Tumblr
    share_url: 
    share_title: 
    share_link:

  - name: Steam
    icon: steam
    username: 
    url: 
    desc: Friend me on Steam
    share_url: 
    share_title: 
    share_link:

  - name: Dribbble
    icon: dribbble
    username: 
    url: 
    desc: Follow me on Dribble

  - name: Vimeo
    icon: vimeo-square
    username: 
    url: 
    desc: Follow me on Vimeo

  - name: Vine
    icon: vine
    username: 
    url: 
    desc: Follow me on Vine

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "assets/images/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "assets/images/logo.png"

    os_repo: "https://github.com/wuxiaoxiaoshen/wuxiaoxiaoshen.github.io"
    os_rcs_type: "git"
    os_src: "git@github.com:wuxiaoxiaoshen/wuxiaoxiaoshen.github.io.git"
